# -*- coding: utf-8 -*-
"""Part B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14x9ufYT1wyL2s_1tMPrU2jZkZijeIMKG
"""

import shutil
from pathlib import Path
from datetime import datetime

Path("data").mkdir(exist_ok=True)

source_dir = Path("data")
backup_dir = Path("backup")



backup_dir.mkdir(parents=True, exist_ok=True)

log_file = Path("backup_log.txt")

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

def log(message):
    with open(log_file, "a") as f:
        f.write(f"{datetime.now().isoformat()} - {message}\n")

for file in source_dir.iterdir():

    if file.suffix in [".csv", ".json"]:

        new_name = f"{file.stem}_{timestamp}{file.suffix}"
        destination = backup_dir / new_name

        shutil.copy2(file, destination)

        log(f"Copied {file.name} -> {destination.name}")

print("Backup completed")



