# -*- coding: utf-8 -*-
"""Part A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14x9ufYT1wyL2s_1tMPrU2jZkZijeIMKG
"""

import csv
import json
from pathlib import Path
from datetime import datetime
from collections import defaultdict

data_folder = Path(".")

csv_files = list(data_folder.glob("data*.csv"))

all_rows = []

for file in csv_files:
    with open(file, "r", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            row["qty"] = int(row["qty"])
            row["price"] = float(row["price"])
            all_rows.append(row)


unique_rows = []
seen = set()

for row in all_rows:
    key = (row["date"], row["product"], row["qty"], row["price"])
    if key not in seen:
        seen.add(key)
        unique_rows.append(row)

unique_rows.sort(key=lambda x: x["date"])

revenue_by_product = defaultdict(float)

for row in unique_rows:
    revenue = row["qty"] * row["price"]
    revenue_by_product[row["product"]] += revenue

with open("merged_sales.csv", "w", newline="") as f:
    fieldnames = ["date", "product", "qty", "price"]
    writer = csv.DictWriter(f, fieldnames=fieldnames)

    writer.writeheader()
    writer.writerows(unique_rows)

total_revenue = sum(revenue_by_product.values())

output = {
    "metadata": {
        "files_processed": len(csv_files),
        "total_rows": len(unique_rows),
        "total_revenue": total_revenue,
        "generated_at": datetime.now().isoformat()
    },
    "revenue_by_product": revenue_by_product
}

with open("revenue_summary.json", "w") as f:
    json.dump(output, f, indent=2)

print("Pipeline completed successfully!")

